# Generated by Django 5.1.2 on 2025-02-11 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0003_remove_subscribe_user'),
        ('user', '0002_profile_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subscribes.subscribe'),
        ),
    ]
