# Generated by Django 5.1.2 on 2025-02-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qrcodes_created',
            field=models.IntegerField(default=0),
        ),
    ]
