# Generated by Django 5.1.2 on 2025-02-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0002_alter_subscribe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
    ]
