# Generated by Django 5.1.2 on 2025-01-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qrc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
