# Generated by Django 5.1.2 on 2025-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qrc', '0002_alter_qrcodes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
