# Generated by Django 5.1.2 on 2025-02-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qrc', '0003_alter_qrcodes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='date_delete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
