# Generated by Django 5.1.2 on 2025-02-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qrc', '0004_qrcodes_date_delete_qrcodes_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='qrcode_img',
            field=models.ImageField(unique=True, upload_to='images/qrcodes'),
        ),
    ]
