# Generated by Django 5.1.2 on 2025-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qrc', '0005_alter_qrcodes_qrcode_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='qrcode_img',
            field=models.ImageField(upload_to='images/qrcodes'),
        ),
    ]
