# Generated by Django 5.1.2 on 2025-03-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_qrc', '0008_alter_qrcodes_qrcode_img'),
        ('subscribes', '0004_alter_subscribe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='subscribe_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribes.subscribe'),
        ),
    ]
